[package]
name = "SnakeOS"
version = "0.1.0"
authors = ["Stan Mijten"]
edition = "2021"

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.14.10"
pc-keyboard = "0.5.0"
pic8259 = "0.10.1"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]


